# Generated by Django 4.2.16 on 2026-04-20 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('search', 'Search'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase'), ('wishlist', 'Wishlist')], max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interactions',
                'indexes': [models.Index(fields=['user', 'action'], name='interaction_user_id_c15036_idx'), models.Index(fields=['product', 'action'], name='interaction_product_19c7ff_idx')],
            },
        ),
    ]
