# Generated by Django 4.2.16 on 2026-05-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Administrator'), ('delivery', 'Delivery Personnel')], default='customer', max_length=15),
        ),
    ]
